//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class Geocode
    {
        public long ID { get; set; }
        public long ResourceID { get; set; }
        public System.Data.Spatial.DbGeography location { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
    
}
