//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class ksgmedia
    {
        public long ID { get; set; }
        public long ResourceID { get; set; }
        public System.Guid KSGObjectID { get; set; }
        public int TypeID { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
    
        public virtual ksgmediatype ksgmediatype { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ksgobject ksgobject { get; set; }
    }
    
}
