//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class ksgobject
    {
        public ksgobject()
        {
            this.ksgmedias = new HashSet<ksgmedia>();
            this.ksgobjectproperties = new HashSet<ksgobjectproperty>();
            this.ksgparents = new HashSet<ksgparent>();
            this.ksgparents1 = new HashSet<ksgparent>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public Nullable<long> DefaultPicID { get; set; }
        public long DescriptionID { get; set; }
        public System.Guid AuthorID { get; set; }
        public Nullable<System.Guid> DefaultParentID { get; set; }
        public Nullable<bool> CoreObject { get; set; }
        public Nullable<bool> Category { get; set; }
    
        public virtual ICollection<ksgmedia> ksgmedias { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Resource Resource1 { get; set; }
        public virtual ICollection<ksgobjectproperty> ksgobjectproperties { get; set; }
        public virtual ICollection<ksgparent> ksgparents { get; set; }
        public virtual ICollection<ksgparent> ksgparents1 { get; set; }
    }
    
}
