//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class ksgobjectproperty
    {
        public long ID { get; set; }
        public System.Guid ksgobjectid { get; set; }
        public long ksgpropertyid { get; set; }
        public Nullable<long> ValueID { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual ksgproperty ksgproperty { get; set; }
        public virtual ksgobject ksgobject { get; set; }
    }
    
}
