//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class ksgproperty
    {
        public ksgproperty()
        {
            this.ksgobjectproperties = new HashSet<ksgobjectproperty>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public long ValueTypeID { get; set; }
        public Nullable<int> UpVotes { get; set; }
        public Nullable<int> DownVotes { get; set; }
    
        public virtual ICollection<ksgobjectproperty> ksgobjectproperties { get; set; }
        public virtual Resource Resource { get; set; }
    }
    
}
