//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class ksgvotetype
    {
        public ksgvotetype()
        {
            this.ksgvotes = new HashSet<ksgvote>();
        }
    
        public byte ID { get; set; }
        public string Descriptoin { get; set; }
    
        public virtual ICollection<ksgvote> ksgvotes { get; set; }
    }
    
}
