//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ksg.Models
{
    public partial class ksgobjectsEntities1 : DbContext
    {
        public ksgobjectsEntities1()
            : base("name=ksgobjectsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ksgbehavior> ksgbehaviors { get; set; }
        public DbSet<ksgbehaviortrigger> ksgbehaviortriggers { get; set; }
        public DbSet<ksgcontext> ksgcontexts { get; set; }
        public DbSet<ksgmedia> ksgmedias { get; set; }
        public DbSet<ksgmediatype> ksgmediatypes { get; set; }
        public DbSet<ksgparent> ksgparents { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<ResourceType> ResourceTypes { get; set; }
        public DbSet<ksgvote> ksgvotes { get; set; }
        public DbSet<ksgvotetype> ksgvotetypes { get; set; }
        public DbSet<ksgobjectproperty> ksgobjectproperties { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<ksgproperty> ksgproperties { get; set; }
        public DbSet<Geocode> Geocodes { get; set; }
        public DbSet<ksgobject> ksgobjects { get; set; }
    }
}
