//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ksg.Models
{
    public partial class Resource
    {
        public Resource()
        {
            this.ksgmedias = new HashSet<ksgmedia>();
            this.ksgobjectproperties = new HashSet<ksgobjectproperty>();
            this.ksgproperties = new HashSet<ksgproperty>();
            this.Geocodes = new HashSet<Geocode>();
            this.ksgobjects = new HashSet<ksgobject>();
            this.ksgobjects1 = new HashSet<ksgobject>();
        }
    
        public long ID { get; set; }
        public byte ResourceTypeID { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<ksgmedia> ksgmedias { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual ICollection<ksgobjectproperty> ksgobjectproperties { get; set; }
        public virtual ICollection<ksgproperty> ksgproperties { get; set; }
        public virtual ICollection<Geocode> Geocodes { get; set; }
        public virtual ICollection<ksgobject> ksgobjects { get; set; }
        public virtual ICollection<ksgobject> ksgobjects1 { get; set; }
    }
    
}
